Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,59 +1,189 @@
 workflows:
-  android-workflow:
-    name: Ionic Cordova Android Workflow
-    max_build_duration: 120
+  ios-workflow:
+    name: iOS workflow
     environment:
-      android_signing:
-        - keystore_reference
       groups:
-        - google_play
+      # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
+        - appstore_credentials # <-- (APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
+          # APP_STORE_CONNECT_ISSUER_ID <-- Put your App Store Connect Issuer Id here 
+          # APP_STORE_CONNECT_KEY_IDENTIFIER <-- Put your App Store Connect Key Identifier here 
+          # APP_STORE_CONNECT_PRIVATE_KEY <-- Put your App Store Connect Private Key here
+          # <-- (CERTIFICATE_PRIVATE_KEY - Put your Certificate Private Key here)
       vars:
-        PACKAGE_NAME: "com.application.laser13"
-        GOOGLE_PLAY_TRACK: alpha
-      node: latest
+        XCODE_WORKSPACE: "platforms/ios/Laser13.xcworkspace" # <-- Put the name of your workspace here.
+        XCODE_SCHEME: "Laser13" # <-- Put the name of your scheme here.       
+        BUNDLE_ID: "com.application.laser13" # <-- Put your Bundle Id here.
+      xcode: latest
+      node: v16.11.1
+      npm: 6
+    cache:
+      cache_paths:
+        - $CM_BUILD_DIR/node_modules
     scripts:
-      - name: Install npm dependencies and update Cordova version
-        script: | 
+      - name: Install dependencies
+        script: |
           npm install
-          npm ci # equivalent of npm install for CI systems.
-            # Requires package-lock.json or npm-shrinkwrap.json to be present
+          npm ci
           cvm install 9.0.0
-          cvm use 9.0.0 
-      - name: Setup Cordova Android platform
-        script: | 
-          ionic cordova platform remove android --nosave
-          ionic cordova platform add android \
-            --confirm \
-            --no-interactive \
-            --noresources 
-      - name: Build Android Cordova App
-        script: | 
-          ionic cordova build android \
-            --release \
-            --no-interactive \
-            --prod \
-            --device
-    - name: Sign APK
-      script: | 
-        APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" | head -1)
-        jarsigner \
-          -sigalg SHA1withRSA \
-          -digestalg SHA1 \
-          -keystore $CM_KEYSTORE_PATH \
-          -storepass $CM_KEYSTORE_PASSWORD \
-          -keypass $CM_KEY_PASSWORD \
-          $APK_PATH $CM_KEY_ALIAS         
+          cvm use 9.0.0
+      - name: Setup iOS
+        script: |
+          cordova platform remove ios --nosave
+          cordova platform add ios --confirm --no-interactive --noresources --save  
+      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
+        script: |
+          keychain initialize
+      - name: Fetch signing files
+        script: |
+          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
+      - name: Add certificates to keychain
+        script: |
+          keychain add-certificates         
+      - name: Set up code signing settings on Xcode project
+        script: |
+          xcode-project use-profiles
+      - name: Build iOS
+        script: |
+          package_type=$(defaults read ~/export_options.plist method)
+          identity=$(defaults read ~/export_options.plist signingCertificate)
+          team=$(defaults read ~/export_options.plist teamID)
+          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
+          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")
+        
+          cat <<EOF > build.json
+              {
+                "ios": {
+                  "release": {
+                    "codeSignIdentity": "$identity",
+                    "developmentTeam": "$team",
+                    "packageType": "$package_type",
+                    "provisioningProfile": "$profile_uuid"
+                  }
+                }
+              }
+          EOF
+          cordova build ios --release --device --buildConfig='build.json' 
     artifacts:
-      - platforms/android/app/build/outputs/**/*.apk
+      - /Users/builder/clone/platforms/ios/build/device/*.ipa
+      - /tmp/xcodebuild_logs/*.log           
     publishing:
+      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
       email:
         recipients:
           - user_1@example.com
           - user_2@example.com
         notify:
-          success: true
-          failure: false
-      google_play:
-        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-        track: internal
-        submit_as_draft: true
+          success: true     # To not receive a notification when a build succeeds
+          failure: false    # To not receive a notification when a build fails
+      slack: 
+        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
+        channel: '#channel-name'
+        notify_on_build_start: true   # To receive a notification when a build starts
+        notify:
+          success: true               # To receive a notification when a build succeeds
+          failure: false              # To not receive a notification when a build fails
+      app_store_connect:                 
+        api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
+        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
+        issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
+        submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
+        # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
+        #      - group name 1
+        #      - group name 2  
+  android-workflow:
+    name: Android workflow
+    environment:
+      ndk: r22b
+      java: 1.8
+      groups:
+        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
+        - keystore_credentials # <-- (Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS)
+          # KEYSTORE <-- Put your keystore file here
+          # KEYSTORE_PASSWORD <-- Put your keystore password here
+          # KEY_ALIAS_PASSWORD <-- Put your keystore alias password here
+          # KEY_ALIAS <-- Put your keystore alias username here
+          # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
+        
+      vars:
+        KEYSTORE_PATH: '/tmp/keystore.keystore'
+      xcode: 12.4
+      node: 12
+      npm: 6 
+    cache:
+      cache_paths:
+        - $CM_BUILD_DIR/node_modules
+    scripts:
+      - name: Install dependencies
+        script: |
+          npm install
+          npm ci
+          cvm install 9.0.0
+          cvm use 9.0.0        
+      - name: Add Android platform
+        script: |
+          set -x
+          cordova platform remove android --nosave
+          cordova platform add android --confirm --no-interactive --noresources
+          cat package.json
+      - name: Build Android
+        script: |
+          set -x
+          set -e
+          export ORG_GRADLE_PROJECT_cdvMinSdkVersion=22
+          #cordova build android
+          #cordova run android --prod --release -- -- --gradleArg=-PcdvMinSdkVersion=20
+          #cordova run android --release -- --keystore=android.keystore  --storePassword=laser13laser13 --alias=android-app-key --password=laser13laser13 --packageType=apk
+          #cordova build android --release --no-interactive --prod --device
+          #echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
+          #UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
+          #jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
+          #zipalign -v 4 $UNSIGNED_APK_PATH app-release.apk
+          #mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')
+          
+          
+          cordova build android --release --no-interactive --prod --device
+          echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
+          UNSIGNED_UNALIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
+          UNSIGNED_APK_PATH=$(echo $UNSIGNED_UNALIGNED_APK_PATH | sed 's/-unsigned/-unsigned-aligned/')
+          SIGNED_APK_PATH=$(echo $UNSIGNED_APK_PATH | sed 's/-unsigned-aligned//')
+          zipalign -v -p 4 $UNSIGNED_UNALIGNED_APK_PATH $UNSIGNED_APK_PATH
+          apksigner sign --ks $KEYSTORE_PATH --ks-pass pass:$KEYSTORE_PASSWORD --ks-key-alias $KEY_ALIAS --key-pass pass:$KEYSTORE_PASSWORD --in $UNSIGNED_APK_PATH --out $SIGNED_APK_PATH
+          rm -rf $UNSIGNED_UNALIGNED_APK_PATH
+          rm -rf $UNSIGNED_APK_PATH
+          
+          
+          #set -x
+          #set -e
+          #export ORG_GRADLE_PROJECT_cdvMinSdkVersion=22
+          #cordova build android --release --no-interactive --prod --device
+          #echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
+          #UNSIGNED_UNALIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
+          #UNSIGNED_APK_PATH=$(echo $UNSIGNED_UNALIGNED_APK_PATH | sed 's/-unsigned/-unsigned-aligned/')
+          #SIGNED_APK_PATH=$(echo $UNSIGNED_APK_PATH | sed 's/-unsigned-aligned//')
+          #zipalign -v -p 4 $UNSIGNED_UNALIGNED_APK_PATH $UNSIGNED_APK_PATH
+          #apksigner sign --ks $KEYSTORE_PATH --ks-pass pass:$KEYSTORE_PASSWORD --ks-key-alias $KEY_ALIAS --key-pass pass:$KEYSTORE_PASSWORD --in $UNSIGNED_APK_PATH --out $SIGNED_APK_PATH
+          #rm -rf $UNSIGNED_UNALIGNED_APK_PATH
+          #rm -rf $UNSIGNED_APK_PATH
+    artifacts:
+      - platforms/android/app/build/outputs/**/*.aab
+      - platforms/android/app/build/outputs/**/*.apk
+      - platforms/android/app/build/outputs/**/mapping.txt
+    publishing:
+        # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
+        email:
+            recipients:
+                - laser13chambery@gmail.com
+            notify:
+              success: true     # To not receive a notification when a build succeeds
+              failure: false    # To not receive a notification when a build fails
+        slack: 
+          # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
+          channel: '#channel-name'
+          notify_on_build_start: true   # To receive a notification when a build starts
+          notify:
+            success: true               # To receive a notification when a build succeeds
+            failure: false              # To not receive a notification when a build fails
+        google_play:
+          # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
+          credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+          track: alpha   
